on: [ push ]

name: Release built gcc

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [x86_64, i686]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - run: |
        chmod +x ./build_compiler.sh
        TARGET=${{ matrix.target }}-elf ./build_compiler.sh

    # Runs a set of commands using the runners shell
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }} 
